name: Deploy

on: [push]

jobs:
  bot:
    needs: server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Initial Setup
        run: |
          npm install yarn -g
      - name: Install and run
        working-directory: client-app
        run: |
          yarn install
          yarn dev
          
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Initial Setup
        run:
          npm install yarn -g
      - name: Build and run
        run:
          yarn
          yarn server:build
          yarn server:run
